### ISSUE TITLE
Problem to generate Metadata JSON using static-wado

### ISSUE THREAD

**Issue by anarnoli** [wayfarer3130/static-wado#6]
Hello,

Being new to static-wado, apologies if I am asking too basic thing. I have a .dcm files for which I want to create metadata json file [metion here](https://v3-docs.ohif.org/configuration/dataSources/dicom-json) which will act as a studylist for the viewer.

To do this I came to know static-wado is a command line tool to generate static WADO metadata and bulkdata files [link](https://v3-docs.ohif.org/configuration/dataSources/static-files).

I configured static-wado repo and ran `StaticWado/build/install/StaticWado/bin/StaticWado -d ./dicomweb ./dicom/study1` which generates below structure but I didn't find Metadata JSON file which should like [this](https://v3-docs.ohif.org/configuration/dataSources/dicom-json#metadata)

<img width="218" alt="Screenshot 2022-01-26 at 7 12 17 PM" src="https://user-images.githubusercontent.com/54370515/151173694-aab3f4a4-8aef-4721-a57f-f5baa453e91c.png">

I wanted to understanding:

- Is my understanding are correct regarding static-wado?
- Someone can please guide which I am doing wrong here?

Please note: In my scenario no DICOM Webserver is involved.

Appreciate help! Thanks

**Comment by wayfarer3130** [comment]
The metadata file doesn't act as the study list for the viewer, the
studylist comes from the studies.gz file - note that is about to be renamed
to studies/index.json.gz instead of studies.gz so it can be served up by
more web servers (having both studies as a path and as a directory caused
problems)

I also pushed a new version to the wayfarer/main branch today - the main
repository has been moved to OHIF, that is:
 https://github.com/OHIF/static-wado.git

The  version on OHIF has fixed the bug where the studies.gz file wasn't
being created, eg:
C:\src\static-wado>dir dicomweb
 Volume in drive C is OS
 Volume Serial Number is 0233-B14F

 Directory of C:\src\static-wado\dicomweb

2022-01-26  10:57 AM    <DIR>          .
2022-01-26  10:57 AM    <DIR>          ..
2022-01-26  10:57 AM    <DIR>          deduplicated
2022-01-26  10:57 AM    <DIR>          instances
2022-01-26  10:57 AM    <DIR>          studies
2022-01-26  10:57 AM               186 studies.gz

Bill.

**Comment by anarnoli** [comment]
Thanks @wayfarer3130.

I cloned the latest repo but it is throwing below error. Is there anything I am missing here?

`main] WARN org.dcm4che.staticwado.Stats.StudyStats - GroupDeduplicated 1 Combine single instance deduplicated objects into sets: 0 instances
[main] WARN org.dcm4che.staticwado.StudyData - No deduplicated instances, not writing study 1.3.12.2.1107.5.4.3.123456789012345.19950922.121803.6
[main] WARN org.dcm4che.staticwado.Stats.StudyStats - StudyStats
[main] WARN org.dcm4che.staticwado.Stats.StudyStats - GroupDeduplicated 1
[main] WARN org.dcm4che.staticwado.Stats.StudyStats - DICOMP10 Read 1
[main] WARN org.dcm4che.staticwado.Stats.StudyStats - Orig TS Image 96
Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path: [/Users/ashishnarnoli/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at org.opencv.osgi.OpenCVNativeLoader.init(OpenCVNativeLoader.java:17)
        at org.dcm4che3.opencv.StreamSegment.<clinit>(StreamSegment.java:76)
        at org.dcm4che3.opencv.NativeImageReader.getNativeImage(NativeImageReader.java:260)
        at org.dcm4che3.opencv.NativeImageReader.read(NativeImageReader.java:251)
        at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.read(DicomImageReader.java:458)
        at org.dcm4che.staticwado.ExtractImageFrames.convertThumbnail(ExtractImageFrames.java:468)
        at org.dcm4che.staticwado.ExtractImageFrames.saveCompressed(ExtractImageFrames.java:212)
        at org.dcm4che.staticwado.StudyManager.importDicom(StudyManager.java:144)
        at org.dcm4che.staticwado.StudyManager.importDicom(StudyManager.java:175)
        at org.dcm4che.staticwado.StudyManager.lambda$scanDicom$0(StudyManager.java:115)
        at org.dcm4che.staticwado.DirScanner.scan(DirScanner.java:33)
        at org.dcm4che.staticwado.DirScanner.scan(DirScanner.java:31)
        at org.dcm4che.staticwado.StudyManager.scanDicom(StudyManager.java:114)
        at org.dcm4che.staticwado.StaticWado.main(StaticWado.java:104)`

**Comment by wayfarer3130** [comment]
You need to set your jni path - on windows, what I do is set it to:
STATIC_WADO_OPTS=-Djava.library.path=c:\bin\StaticWado\Windows-x86-64
but you will have to set the equivalent variable for your OS.  I don't have
binaries for the new Macs.

Bill

**Comment by anarnoli** [comment]
Thanks @wayfarer3130.

For Mac M1 is `STATIC_WADO_OUT_OPTS=-Djava.library.path=/usr/lib/StaticWado/Mac` no supporting?

**Comment by wayfarer3130** [comment]
Thats correct, it isn't supported.  Try running the nodejs version
static-wado-js   That version does no image conversion right now, but that
is a feature that is being worked on.  Or, you could update the libraries
in dcm4che for the JNI libraries (which is the imageio library being used).

Bill

**Comment by cupidchan** [comment]
@wayfarer3130 I thought the JVM will abstract out the platform difference (M1 or not), right? I am using the new M1 machine too and am wondering what is the best way to resolve this issue.

**Comment by wayfarer3130** [comment]
Not for native code it won't.  The problem is the native code is in C,
compiled to a JNI library.  I really have no idea how to get you a build of
it for that system.  Suggest you try the static-wado-js version instead as
that doesn't do any image conversion.

Bill
